# Generated by Django 4.2.7 on 2024-06-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_email_confirmed_emailconfirmationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_customer_service',
            field=models.BooleanField(default=False),
        ),
    ]
