# Generated by Django 4.2.7 on 2024-02-23 18:33

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to=main.models.file_path)),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmwares', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='FirmwareLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('line', models.CharField(max_length=200)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.firmware')),
            ],
        ),
        migrations.AddConstraint(
            model_name='firmware',
            constraint=models.UniqueConstraint(fields=('version', 'car_model'), name='unique_version_car_model'),
        ),
    ]
