# Generated by Django 4.2.7 on 2024-01-11 20:30

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=10, unique=True)),
                ('file', models.FileField(upload_to=main.models.file_path)),
            ],
        ),
        migrations.CreateModel(
            name='FirmwareLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('line', models.CharField(max_length=200)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.firmware')),
            ],
        ),
    ]
