# Generated by Django 4.2.7 on 2024-02-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_registration_date'),
        ('main', '0002_alter_firmware_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmwares', to='cars.carmodel'),
        ),
    ]
