# Generated by Django 4.2.7 on 2024-02-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_firmware_car_model'),
        ('cars', '0003_car_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='installed_firmware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.firmware'),
        ),
    ]
