# Generated by Django 4.2.7 on 2024-06-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_installed_firmware'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cars.car')),
            ],
        ),
    ]
