# Generated by Django 4.2.7 on 2024-06-23 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#FFFFFF', 'White'), ('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FF00FF', 'Violet'), ('#00FFFF', 'Cyan')], default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='horsepower',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='max_speed_km',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='total_weight_kg',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
